sudo: false
language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION 'set scalaJSStage in Global := FastOptStage' compile 'testOnly T5514 scala.util.parsing.combinator.RegexParsersTest'
scala:
  - 2.11.1
jdk:
  - openjdk6
  - openjdk7
notifications:
  email:
    - sjrdoeraene@gmail.com

# if we get weird timeouts, see https://github.com/spray/spray/pull/233
# 'set concurrentRestrictions in Global += Tags.limit(Tags.Test, 1)'
